[tools]
rotrieve = { source = "roblox/rotriever", version = "=0.5.0-rc.4" }
rojo = { source = "rojo-rbx/rojo", version = "6.0.2" }
selene = { source = "Kampfkarren/selene", version = "0.14.0" }
testez = { source = "roblox/testez", version = "0.3.2" }
