[tools]
rotrieve = { source = "roblox/rotriever", version = "0.5.4" }
selene = { source = "Roblox/Kampfkarren-selene", version = "0.19.1" }
stylua = { source = "Roblox/JohnnyMorganz-StyLua", version = "0.13.1" }
testez = { source = "roblox/testez", version = "0.3.2" }
