-- introspection mock common types
-- ROBLOX REMOVEME: remove the file when introspectionFromSchema is implemented

local introspection1And3Common = {
	{
		kind = "OBJECT",
		name = "Query",
		description = nil,
		specifiedByUrl = nil,
		fields = {
			{
				name = "foo",
				description = nil,
				args = {},
				type = {
					kind = "SCALAR",
					name = "String",
					ofType = nil,
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
		},
		inputFields = nil,
		interfaces = {},
		enumValues = nil,
		possibleTypes = nil,
	},
	{
		kind = "SCALAR",
		name = "String",
		description = "The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.",
		specifiedByUrl = nil,
		fields = nil,
		inputFields = nil,
		interfaces = nil,
		enumValues = nil,
		possibleTypes = nil,
	},
	{
		kind = "SCALAR",
		name = "Boolean",
		description = "The `Boolean` scalar type represents `true` or `false`.",
		specifiedByUrl = nil,
		fields = nil,
		inputFields = nil,
		interfaces = nil,
		enumValues = nil,
		possibleTypes = nil,
	},
}

local allCommon = {
	{
		kind = "OBJECT",
		name = "__Schema",
		description = "A GraphQL Schema defines the capabilities of a GraphQL server. It exposes all available types and directives on the server, as well as the entry points for query, mutation, and subscription operations.",
		specifiedByUrl = nil,
		fields = {
			{
				name = "description",
				description = nil,
				args = {},
				type = {
					kind = "SCALAR",
					name = "String",
					ofType = nil,
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "types",
				description = "A list of all types supported by this server.",
				args = {},
				type = {
					kind = "NON_NULL",
					name = nil,
					ofType = {
						kind = "LIST",
						name = nil,
						ofType = {
							kind = "NON_NULL",
							name = nil,
							ofType = {
								kind = "OBJECT",
								name = "__Type",
								ofType = nil,
							},
						},
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "queryType",
				description = "The type that query operations will be rooted at.",
				args = {},
				type = {
					kind = "NON_NULL",
					name = nil,
					ofType = {
						kind = "OBJECT",
						name = "__Type",
						ofType = nil,
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "mutationType",
				description = "If this server supports mutation, the type that mutation operations will be rooted at.",
				args = {},
				type = {
					kind = "OBJECT",
					name = "__Type",
					ofType = nil,
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "subscriptionType",
				description = "If this server support subscription, the type that subscription operations will be rooted at.",
				args = {},
				type = {
					kind = "OBJECT",
					name = "__Type",
					ofType = nil,
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "directives",
				description = "A list of all directives supported by this server.",
				args = {},
				type = {
					kind = "NON_NULL",
					name = nil,
					ofType = {
						kind = "LIST",
						name = nil,
						ofType = {
							kind = "NON_NULL",
							name = nil,
							ofType = {
								kind = "OBJECT",
								name = "__Directive",
								ofType = nil,
							},
						},
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
		},
		inputFields = nil,
		interfaces = {},
		enumValues = nil,
		possibleTypes = nil,
	},
	{
		kind = "OBJECT",
		name = "__Type",
		description = "The fundamental unit of any GraphQL Schema is the type. There are many kinds of types in GraphQL as represented by the `__TypeKind` enum.\n\nDepending on the kind of a type, certain fields describe information about that type. Scalar types provide no information beyond a name, description and optional `specifiedByUrl`, while Enum types provide their values. Object and Interface types provide the fields they describe. Abstract types, Union and Interface, provide the Object types possible at runtime. List and NonNull types compose other types.",
		specifiedByUrl = nil,
		fields = {
			{
				name = "kind",
				description = nil,
				args = {},
				type = {
					kind = "NON_NULL",
					name = nil,
					ofType = {
						kind = "ENUM",
						name = "__TypeKind",
						ofType = nil,
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "name",
				description = nil,
				args = {},
				type = {
					kind = "SCALAR",
					name = "String",
					ofType = nil,
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "description",
				description = nil,
				args = {},
				type = {
					kind = "SCALAR",
					name = "String",
					ofType = nil,
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "specifiedByUrl",
				description = nil,
				args = {},
				type = {
					kind = "SCALAR",
					name = "String",
					ofType = nil,
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "fields",
				description = nil,
				args = {
					{
						name = "includeDeprecated",
						description = nil,
						type = {
							kind = "SCALAR",
							name = "Boolean",
							ofType = nil,
						},
						defaultValue = "false",
						isDeprecated = false,
						deprecationReason = nil,
					},
				},
				type = {
					kind = "LIST",
					name = nil,
					ofType = {
						kind = "NON_NULL",
						name = nil,
						ofType = {
							kind = "OBJECT",
							name = "__Field",
							ofType = nil,
						},
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "interfaces",
				description = nil,
				args = {},
				type = {
					kind = "LIST",
					name = nil,
					ofType = {
						kind = "NON_NULL",
						name = nil,
						ofType = {
							kind = "OBJECT",
							name = "__Type",
							ofType = nil,
						},
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "possibleTypes",
				description = nil,
				args = {},
				type = {
					kind = "LIST",
					name = nil,
					ofType = {
						kind = "NON_NULL",
						name = nil,
						ofType = {
							kind = "OBJECT",
							name = "__Type",
							ofType = nil,
						},
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "enumValues",
				description = nil,
				args = {
					{
						name = "includeDeprecated",
						description = nil,
						type = {
							kind = "SCALAR",
							name = "Boolean",
							ofType = nil,
						},
						defaultValue = "false",
						isDeprecated = false,
						deprecationReason = nil,
					},
				},
				type = {
					kind = "LIST",
					name = nil,
					ofType = {
						kind = "NON_NULL",
						name = nil,
						ofType = {
							kind = "OBJECT",
							name = "__EnumValue",
							ofType = nil,
						},
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "inputFields",
				description = nil,
				args = {
					{
						name = "includeDeprecated",
						description = nil,
						type = {
							kind = "SCALAR",
							name = "Boolean",
							ofType = nil,
						},
						defaultValue = "false",
						isDeprecated = false,
						deprecationReason = nil,
					},
				},
				type = {
					kind = "LIST",
					name = nil,
					ofType = {
						kind = "NON_NULL",
						name = nil,
						ofType = {
							kind = "OBJECT",
							name = "__InputValue",
							ofType = nil,
						},
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "ofType",
				description = nil,
				args = {},
				type = {
					kind = "OBJECT",
					name = "__Type",
					ofType = nil,
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
		},
		inputFields = nil,
		interfaces = {},
		enumValues = nil,
		possibleTypes = nil,
	},
	{
		kind = "ENUM",
		name = "__TypeKind",
		description = "An enum describing what kind of type a given `__Type` is.",
		specifiedByUrl = nil,
		fields = nil,
		inputFields = nil,
		interfaces = nil,
		enumValues = {
			{
				name = "SCALAR",
				description = "Indicates this type is a scalar.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "OBJECT",
				description = "Indicates this type is an object. `fields` and `interfaces` are valid fields.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "INTERFACE",
				description = "Indicates this type is an interface. `fields`, `interfaces`, and `possibleTypes` are valid fields.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "UNION",
				description = "Indicates this type is a union. `possibleTypes` is a valid field.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "ENUM",
				description = "Indicates this type is an enum. `enumValues` is a valid field.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "INPUT_OBJECT",
				description = "Indicates this type is an input object. `inputFields` is a valid field.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "LIST",
				description = "Indicates this type is a list. `ofType` is a valid field.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "NON_NULL",
				description = "Indicates this type is a non-nil. `ofType` is a valid field.",
				isDeprecated = false,
				deprecationReason = nil,
			},
		},
		possibleTypes = nil,
	},
	{
		kind = "OBJECT",
		name = "__Field",
		description = "Object and Interface types are described by a list of Fields, each of which has a name, potentially a list of arguments, and a return type.",
		specifiedByUrl = nil,
		fields = {
			{
				name = "name",
				description = nil,
				args = {},
				type = {
					kind = "NON_NULL",
					name = nil,
					ofType = {
						kind = "SCALAR",
						name = "String",
						ofType = nil,
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "description",
				description = nil,
				args = {},
				type = {
					kind = "SCALAR",
					name = "String",
					ofType = nil,
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "args",
				description = nil,
				args = {
					{
						name = "includeDeprecated",
						description = nil,
						type = {
							kind = "SCALAR",
							name = "Boolean",
							ofType = nil,
						},
						defaultValue = "false",
						isDeprecated = false,
						deprecationReason = nil,
					},
				},
				type = {
					kind = "NON_NULL",
					name = nil,
					ofType = {
						kind = "LIST",
						name = nil,
						ofType = {
							kind = "NON_NULL",
							name = nil,
							ofType = {
								kind = "OBJECT",
								name = "__InputValue",
								ofType = nil,
							},
						},
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "type",
				description = nil,
				args = {},
				type = {
					kind = "NON_NULL",
					name = nil,
					ofType = {
						kind = "OBJECT",
						name = "__Type",
						ofType = nil,
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "isDeprecated",
				description = nil,
				args = {},
				type = {
					kind = "NON_NULL",
					name = nil,
					ofType = {
						kind = "SCALAR",
						name = "Boolean",
						ofType = nil,
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "deprecationReason",
				description = nil,
				args = {},
				type = {
					kind = "SCALAR",
					name = "String",
					ofType = nil,
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
		},
		inputFields = nil,
		interfaces = {},
		enumValues = nil,
		possibleTypes = nil,
	},
	{
		kind = "OBJECT",
		name = "__InputValue",
		description = "Arguments provided to Fields or Directives and the input fields of an InputObject are represented as Input Values which describe their type and optionally a default value.",
		specifiedByUrl = nil,
		fields = {
			{
				name = "name",
				description = nil,
				args = {},
				type = {
					kind = "NON_NULL",
					name = nil,
					ofType = {
						kind = "SCALAR",
						name = "String",
						ofType = nil,
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "description",
				description = nil,
				args = {},
				type = {
					kind = "SCALAR",
					name = "String",
					ofType = nil,
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "type",
				description = nil,
				args = {},
				type = {
					kind = "NON_NULL",
					name = nil,
					ofType = {
						kind = "OBJECT",
						name = "__Type",
						ofType = nil,
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "defaultValue",
				description = "A GraphQL-formatted string representing the default value for this input value.",
				args = {},
				type = {
					kind = "SCALAR",
					name = "String",
					ofType = nil,
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "isDeprecated",
				description = nil,
				args = {},
				type = {
					kind = "NON_NULL",
					name = nil,
					ofType = {
						kind = "SCALAR",
						name = "Boolean",
						ofType = nil,
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "deprecationReason",
				description = nil,
				args = {},
				type = {
					kind = "SCALAR",
					name = "String",
					ofType = nil,
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
		},
		inputFields = nil,
		interfaces = {},
		enumValues = nil,
		possibleTypes = nil,
	},
	{
		kind = "OBJECT",
		name = "__EnumValue",
		description = "One possible value for a given Enum. Enum values are unique values, not a placeholder for a string or numeric value. However an Enum value is returned in a JSON response as a string.",
		specifiedByUrl = nil,
		fields = {
			{
				name = "name",
				description = nil,
				args = {},
				type = {
					kind = "NON_NULL",
					name = nil,
					ofType = {
						kind = "SCALAR",
						name = "String",
						ofType = nil,
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "description",
				description = nil,
				args = {},
				type = {
					kind = "SCALAR",
					name = "String",
					ofType = nil,
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "isDeprecated",
				description = nil,
				args = {},
				type = {
					kind = "NON_NULL",
					name = nil,
					ofType = {
						kind = "SCALAR",
						name = "Boolean",
						ofType = nil,
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "deprecationReason",
				description = nil,
				args = {},
				type = {
					kind = "SCALAR",
					name = "String",
					ofType = nil,
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
		},
		inputFields = nil,
		interfaces = {},
		enumValues = nil,
		possibleTypes = nil,
	},
	{
		kind = "OBJECT",
		name = "__Directive",
		description = "A Directive provides a way to describe alternate runtime execution and type validation behavior in a GraphQL document.\n\nIn some cases, you need to provide options to alter GraphQL's execution behavior in ways field arguments will not suffice, such as conditionally including or skipping a field. Directives provide this by describing additional information to the executor.",
		specifiedByUrl = nil,
		fields = {
			{
				name = "name",
				description = nil,
				args = {},
				type = {
					kind = "NON_NULL",
					name = nil,
					ofType = {
						kind = "SCALAR",
						name = "String",
						ofType = nil,
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "description",
				description = nil,
				args = {},
				type = {
					kind = "SCALAR",
					name = "String",
					ofType = nil,
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "isRepeatable",
				description = nil,
				args = {},
				type = {
					kind = "NON_NULL",
					name = nil,
					ofType = {
						kind = "SCALAR",
						name = "Boolean",
						ofType = nil,
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "locations",
				description = nil,
				args = {},
				type = {
					kind = "NON_NULL",
					name = nil,
					ofType = {
						kind = "LIST",
						name = nil,
						ofType = {
							kind = "NON_NULL",
							name = nil,
							ofType = {
								kind = "ENUM",
								name = "__DirectiveLocation",
								ofType = nil,
							},
						},
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "args",
				description = nil,
				args = {},
				type = {
					kind = "NON_NULL",
					name = nil,
					ofType = {
						kind = "LIST",
						name = nil,
						ofType = {
							kind = "NON_NULL",
							name = nil,
							ofType = {
								kind = "OBJECT",
								name = "__InputValue",
								ofType = nil,
							},
						},
					},
				},
				isDeprecated = false,
				deprecationReason = nil,
			},
		},
		inputFields = nil,
		interfaces = {},
		enumValues = nil,
		possibleTypes = nil,
	},
	{
		kind = "ENUM",
		name = "__DirectiveLocation",
		description = "A Directive can be adjacent to many parts of the GraphQL language, a __DirectiveLocation describes one such possible adjacencies.",
		specifiedByUrl = nil,
		fields = nil,
		inputFields = nil,
		interfaces = nil,
		enumValues = {
			{
				name = "QUERY",
				description = "Location adjacent to a query operation.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "MUTATION",
				description = "Location adjacent to a mutation operation.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "SUBSCRIPTION",
				description = "Location adjacent to a subscription operation.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "FIELD",
				description = "Location adjacent to a field.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "FRAGMENT_DEFINITION",
				description = "Location adjacent to a fragment definition.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "FRAGMENT_SPREAD",
				description = "Location adjacent to a fragment spread.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "INLINE_FRAGMENT",
				description = "Location adjacent to an inline fragment.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "VARIABLE_DEFINITION",
				description = "Location adjacent to a variable definition.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "SCHEMA",
				description = "Location adjacent to a schema definition.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "SCALAR",
				description = "Location adjacent to a scalar definition.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "OBJECT",
				description = "Location adjacent to an object type definition.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "FIELD_DEFINITION",
				description = "Location adjacent to a field definition.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "ARGUMENT_DEFINITION",
				description = "Location adjacent to an argument definition.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "INTERFACE",
				description = "Location adjacent to an interface definition.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "UNION",
				description = "Location adjacent to a union definition.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "ENUM",
				description = "Location adjacent to an enum definition.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "ENUM_VALUE",
				description = "Location adjacent to an enum value definition.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "INPUT_OBJECT",
				description = "Location adjacent to an input object type definition.",
				isDeprecated = false,
				deprecationReason = nil,
			},
			{
				name = "INPUT_FIELD_DEFINITION",
				description = "Location adjacent to an input object field definition.",
				isDeprecated = false,
				deprecationReason = nil,
			},
		},
		possibleTypes = nil,
	},
}
return {
	allCommon = allCommon,
	introspection1And3Common = introspection1And3Common
}
