--[[
 * Creates an object map with the same keys as `map` and values generated by
 * running each value of `map` thru `fn`.
 ]]
return function(map, fn)
    local result = {}
	for key, value in pairs(map) do
		result[key] = fn(value, key)
	end
    return result
end
